{% set name = "thalassa" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thalassa-{{ version }}.tar.gz
  sha256: c8c661445c11745d46b61bd8162d3b77dea7b3cbd7768c7f0eaacf7a9c9cea57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9,<3.11
    - geos
    - cartopy
    - datashader
    - geopandas
    - geoviews
    - holoviews
    - numpy <1.24
    - pandas
    - shapely
    - xarray

test:
  requires:
    - pip
    - pytest
  imports:
    - thalassa.api
    - thalassa.utils
    - thalassa.normalization

about:
  home: https://github.com/ec-jrc/thalassa
  summary: 'Efficient, extendable visualizer for large unstructured meshes written in Python'
  description: |
    Thalassa ia a library for visualizing unstructured mesh data.
    It builds upon geoviews and datashader and can easily handle meshes with millions of nodes interactively.
  license: EUPL-1.2
  license_file: LICENSE
  doc_url: https://thalassa.readthedocs.io/
  dev_url: https://github.com/oceanmodeling/thalassa

extra:
  recipe-maintainers:
    - brey
    - pmav99
