{% set name = "thalassa" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thalassa-{{ version }}.tar.gz
  sha256: 73e23973396ae1235e71ea23ed1d6d6a5fe20676d311a5b6eb5bd3f6d43fe2ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9
    - geos
    - bokeh >=3.0
    - bottleneck
    - cartopy
    - cfgrib
    - dask
    - datashader
    - geopandas
    - geoviews
    - holoviews >=1.15
    - ipywidgets
    - numbagg
    - numpy
    - numpy-indexed
    - pandas
    - scipy
    - shapely
    - xarray
    - zarr

test:
  requires:
    - pip
    - pytest
  imports:
    - thalassa.api
    - thalassa.plotting
    - thalassa.utils
    - thalassa.normalization

about:
  home: https://github.com/ec-jrc/thalassa
  summary: 'Efficient, extendable visualizer for large unstructured meshes written in Python'
  description: |
    Thalassa ia a library for visualizing unstructured mesh data.
    It builds upon geoviews and datashader and can easily handle meshes with millions of nodes interactively.
  license: EUPL-1.2
  license_file: LICENSE
  doc_url: https://thalassa.readthedocs.io/
  dev_url: https://github.com/oceanmodeling/thalassa

extra:
  recipe-maintainers:
    - brey
    - pmav99
